### ISSUE TITLE
ML-Tutorial-Experiment/Experiments/tf_LeNet5.ipynb

### ISSUE THREAD

**Issue by huangnengCSU** [jiqizhixin/ML-Tutorial-Experiment#6]
with tf.variable_scope('layer6-fc2'):
        fc2_weights = tf.get_variable('weight', [FC_SIZE, NUM_LABELS],
                                      initializer=tf.truncated_normal_initializer(stddev=0.1))
        if regularizer != None:
            tf.add_to_collection('losses', regularizer(fc1_weights))

        fc2_biases = tf.get_variable('bias', [NUM_LABELS], initializer=tf.constant_initializer(0.1))
        logit = tf.matmul(fc1, fc2_weights) + fc2_biases
    return logit

inner the function tf.add_to_collection() should be regularizer(fc2_weights) instead of regularizer(fc1_weights)

**Comment by HoratioJSY** [comment]
thanks, we have modified...
