### ISSUE TITLE
小白求问

### ISSUE THREAD

**Issue by XMQLing** [jiqizhixin/ML-Tutorial-Experiment#8]
OSError: Unable to open file (Unable to open file: name = 'generator', errno = 2, error message = 'no such file or directory', flags = 0, o_flags = 0)

纯新手，求问这是为什么呢

**Comment by PeterHuang2015** [comment]
It's just `file not found error`(文件没找到), pls try to solve it by yourself.

**Comment by HoratioJSY** [comment]
需要先运行train()函数，里面的g.save_weights('generator', True)和d.save_weights('discriminator', True)会保存训练后的模型，才能打开generator

**Comment by XMQLing** [comment]
> It's just `file not found error`(文件没找到), pls try to solve it by yourself.

OK

**Comment by XMQLing** [comment]
> 需要先运行train()函数，里面的g.save_weights('generator', True)和d.save_weights('discriminator', True)会保存训练后的模型，才能打开generator

感谢！
